services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: '192.168.68.11' #update, assign open ip manually
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      TZ: 'America/Asuncion' # update according to your timezone
      WEBPASSWORD: 'H4lc0n#05' #update password
    volumes:
      - '/home/username/pihole/etc-pihole:/etc/pihole' #update
      - '/home/username/pihole/etc-dnsmasq.d:/etc/dnsmasq.d' #update
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 192.168.68.0/24 #update if needed
          gateway: 192.168.68.1 #update if needed
